name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/Semantic-version@4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        echo "Iniciando login version: $NEW_VERSION"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del login"
    - name: Build Docker Image
      run: |
        docker build -t jdavid198/docker-github:1.1.1 .
        docker build -t jdavid198/docker-github:latest .
    - name: Push Docker Image
      run: |
        docker push jdavid198/docker-github:1.1.1
        docker push jdavid198/docker-github:latest


